In [1]:
import pandas as pd
import numpy as np

train: control(1,2,3,4)+adhd(7,8,9)


test: control(5)+adhd(10)

- Control dataset

In [35]:
control_Theta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['Theta']])
df = df.head(490).T
df.index=[1]
control_Theta = control_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['Theta']])
df = df.T
df.index=[2]
control_Theta= control_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['Theta']])
df = df.T
df.index=[3]
control_Theta= control_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['Theta']])
df = df.T
df.index=[4]
control_Theta= control_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['Theta']])
df = df.T
df.index=[5]
control_Theta= control_Theta.append(df)



control_Theta = control_Theta.dropna(axis=1)   # column
control_Theta


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
1,0.332158,0.642957,0.458338,0.528602,0.683617,0.332158,0.642957,0.458338,0.528602,0.683617,...,0.212551,0.317664,0.561361,0.836981,0.609319,0.212551,0.317664,0.561361,0.836981,0.609319
2,2.857617,1.294798,1.600999,7.868133,2.315394,2.857617,1.294798,1.600999,7.868133,2.315394,...,1.352801,0.305441,0.644878,1.735645,1.408395,1.352801,0.305441,0.644878,1.735645,1.408395
3,1.191336,0.528186,0.798593,0.498767,1.283596,1.191336,0.528186,0.798593,0.498767,1.283596,...,1.334645,1.827253,0.945240,0.868289,1.478432,0.461807,0.824516,0.747099,0.958553,0.778781
4,0.420250,0.346276,0.272355,0.827547,1.578074,0.420250,0.346276,0.272355,0.827547,1.578074,...,1.529931,0.567498,0.449727,0.675753,1.456528,1.529931,0.567498,0.449727,0.675753,1.456528
5,4.380045,0.371932,1.221854,2.046963,2.241406,4.380045,0.371932,1.221854,2.046963,2.241406,...,0.640339,1.748845,0.229628,1.306018,1.034505,0.640339,1.748845,0.229628,1.306018,1.034505

In [36]:
control_Alpha = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['Alpha']])
df = df.head(490).T
df.index=[1]
control_Alpha = control_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[2]
control_Alpha= control_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[3]
control_Alpha= control_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[4]
control_Alpha= control_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[5]
control_Alpha= control_Alpha.append(df)



control_Alpha = control_Alpha.dropna(axis=1)   # column
control_Alpha

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
1,0.175801,0.259134,0.685974,0.753501,0.293142,0.175801,0.259134,0.685974,0.753501,0.293142,...,0.218744,0.217909,0.344075,0.630913,0.301278,0.218744,0.217909,0.344075,0.630913,0.301278
2,0.347631,0.368325,1.816854,1.742926,0.350514,0.347631,0.368325,1.816854,1.742926,0.350514,...,1.104475,0.136151,1.268626,1.506870,1.486845,1.104475,0.136151,1.268626,1.506870,1.486845
3,0.630867,0.305691,0.777314,1.300691,0.633542,0.630867,0.305691,0.777314,1.300691,0.633542,...,0.390894,0.809746,0.727880,1.039629,0.807926,0.315117,0.549842,0.528654,0.739086,0.738878
4,0.495860,0.514494,0.426581,2.019397,1.612966,0.495860,0.514494,0.426581,2.019397,1.612966,...,0.553306,0.336822,0.644059,1.257820,1.192617,0.553306,0.336822,0.644059,1.257820,1.192617
5,0.660897,1.067346,0.227851,1.530523,0.926018,0.660897,1.067346,0.227851,1.530523,0.926018,...,0.892834,1.173559,0.371134,1.269681,1.356544,0.892834,1.173559,0.371134,1.269681,1.356544

In [4]:
control_Low_beta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['Low_beta']])
df = df.head(490).T
df.index=[1]
control_Low_beta = control_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['Low_beta']])
df = df.T
df.index=[2]
control_Low_beta= control_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['Low_beta']])
df = df.T
df.index=[3]
control_Low_beta= control_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['Low_beta']])
df = df.T
df.index=[4]
control_Low_beta= control_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['Low_beta']])
df = df.T
df.index=[5]
control_Low_beta= control_Low_beta.append(df)



control_Low_beta = control_Low_beta.dropna(axis=1)   # column
control_Low_beta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
1,0.068568,0.122800,0.243153,0.974857,0.103136,0.068568,0.122800,0.243153,0.974857,0.103136,...,0.126126,0.152555,0.804952,0.510596,0.148952,0.126126,0.152555,0.804952,0.510596,0.148952
2,0.371081,0.235985,0.573356,0.728103,0.440666,0.371081,0.235985,0.573356,0.728103,0.440666,...,0.416448,0.246998,1.552036,0.778892,0.523793,0.416448,0.246998,1.552036,0.778892,0.523793
3,0.187054,0.357778,0.300475,0.604936,0.233595,0.187054,0.357778,0.300475,0.604936,0.233595,...,0.470591,1.177236,0.540633,1.158921,0.604523,0.456086,0.715299,0.484682,0.846261,0.378149
4,0.960645,0.386155,0.167605,1.134109,0.897473,0.960645,0.386155,0.167605,1.134109,0.897473,...,0.347516,3.090254,0.164111,1.136592,0.646283,0.347516,3.090254,0.164111,1.136592,0.646283
5,0.353199,0.636659,0.189075,0.331557,0.674130,0.353199,0.636659,0.189075,0.331557,0.674130,...,0.297152,0.464621,0.131042,0.604390,0.256675,0.297152,0.464621,0.131042,0.604390,0.256675

In [5]:
control_High_beta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['High_beta']])
df = df.head(490).T
df.index=[1]
control_High_beta = control_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['High_beta']])
df = df.T
df.index=[2]
control_High_beta= control_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['High_beta']])
df = df.T
df.index=[3]
control_High_beta= control_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['High_beta']])
df = df.T
df.index=[4]
control_High_beta= control_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['High_beta']])
df = df.T
df.index=[5]
control_High_beta= control_High_beta.append(df)



control_High_beta = control_High_beta.dropna(axis=1)   # column
control_High_beta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
1,0.114717,0.119161,0.102457,0.437046,0.207148,0.114717,0.119161,0.102457,0.437046,0.207148,...,0.064985,0.227522,0.141397,0.546179,0.103581,0.064985,0.227522,0.141397,0.546179,0.103581
2,0.423699,0.099773,0.537788,0.458094,0.312611,0.423699,0.099773,0.537788,0.458094,0.312611,...,0.182385,0.121158,0.468564,0.513016,0.169158,0.182385,0.121158,0.468564,0.513016,0.169158
3,0.163982,0.655728,0.302804,0.550229,0.175743,0.163982,0.655728,0.302804,0.550229,0.175743,...,0.157659,1.698051,0.354846,1.251608,0.266721,0.170312,2.109567,0.388486,1.017609,0.253784
4,0.477714,1.455983,0.201474,1.667320,0.706912,0.477714,1.455983,0.201474,1.667320,0.706912,...,0.251736,1.138053,0.262465,0.744552,0.354172,0.251736,1.138053,0.262465,0.744552,0.354172
5,0.247059,0.326374,0.100823,0.219076,0.635414,0.247059,0.326374,0.100823,0.219076,0.635414,...,0.190099,0.350407,0.099144,0.304027,0.330589,0.190099,0.350407,0.099144,0.304027,0.330589

In [6]:
control_Gamma = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['Gamma ']])
df = df.head(490).T
df.index=[1]
control_Gamma = control_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['Gamma ']])
df = df.T
df.index=[2]
control_Gamma= control_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['Gamma ']])
df = df.T
df.index=[3]
control_Gamma= control_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['Gamma ']])
df = df.T
df.index=[4]
control_Gamma= control_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['Gamma ']])
df = df.T
df.index=[5]
control_Gamma= control_Gamma.append(df)



control_Gamma = control_Gamma.dropna(axis=1)   # column
control_Gamma

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
1,0.073143,0.083767,0.073224,0.104580,0.071107,0.073143,0.083767,0.073224,0.104580,0.071107,...,0.108800,0.118382,0.061758,0.431881,0.086454,0.108800,0.118382,0.061758,0.431881,0.086454
2,0.117245,0.105164,0.252184,0.189314,0.166669,0.117245,0.105164,0.252184,0.189314,0.166669,...,0.150492,0.081174,0.436024,0.297124,0.185248,0.150492,0.081174,0.436024,0.297124,0.185248
3,0.144762,0.480914,0.113822,0.591946,0.155756,0.144762,0.480914,0.113822,0.591946,0.155756,...,0.186345,1.280200,0.331541,0.981033,0.212069,0.117909,0.732267,0.275362,0.933620,0.174340
4,0.310296,2.125887,0.116311,0.702569,0.351376,0.310296,2.125887,0.116311,0.702569,0.351376,...,0.159534,1.145240,0.174198,0.685328,0.159373,0.159534,1.145240,0.174198,0.685328,0.159373
5,0.101996,0.353386,0.095654,0.113603,0.142634,0.101996,0.353386,0.095654,0.113603,0.142634,...,0.094738,0.193517,0.066769,0.196825,0.071097,0.094738,0.193517,0.066769,0.196825,0.071097

In [7]:
control_y = pd.Series([0]*len(control_Gamma))
control_y.index = control_Gamma.index
control_y

1    0
2    0
3    0
4    0
5    0
dtype: int64

- adhd dataset

In [8]:
adhd_Theta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['Theta']])
df = df.T
df.index=[7]
adhd_Theta = adhd_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['Theta']])
df = df.T
df.index=[8]
adhd_Theta = adhd_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['Theta']])
df = df.T
df.index=[9]
adhd_Theta = adhd_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['Theta']])
df = df.T
df.index=[10]
adhd_Theta = adhd_Theta.append(df)


adhd_Theta = adhd_Theta.dropna(axis=1)   # column
adhd_Theta


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,144.090564,164.162214,146.320972,135.365645,140.392667,144.090564,164.162214,146.320972,135.365645,140.392667,...,3.563141,1.031004,3.536819,1.268879,4.107299,1.474841,0.365848,2.838640,1.258778,2.092410
8,90.534190,98.651231,92.379840,85.611914,84.056584,90.534190,98.651231,92.379840,85.611914,84.056584,...,0.954606,0.899872,6.915874,0.197417,0.806120,0.964724,0.408348,3.587791,0.130414,0.932110
9,117.570611,100.331176,84.212331,90.159698,94.179666,117.570611,100.331176,84.212331,90.159698,94.179666,...,1983.399406,44.677269,46.503565,660.070717,4.340552,643.762352,11.525363,12.034101,160.062192,13.740685
10,203.415632,99.177751,91.285068,85.943236,191.719079,203.415632,99.177751,91.285068,85.943236,191.719079,...,2.159236,0.152251,0.726994,0.000093,7867.043400,2.159236,0.152251,0.726994,0.000093,7867.043400

In [9]:
adhd_Alpha = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['Alpha']])
df = df.T
df.index=[7]
adhd_Alpha = adhd_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['Alpha']])
df = df.T
df.index=[8]
adhd_Alpha = adhd_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['Alpha']])
df = df.T
df.index=[9]
adhd_Alpha = adhd_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['Alpha']])
df = df.T
df.index=[10]
adhd_Alpha = adhd_Alpha.append(df)


adhd_Alpha = adhd_Alpha.dropna(axis=1)   # column
adhd_Alpha


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,47.345218,52.095417,41.021074,39.000685,42.540855,47.345218,52.095417,41.021074,39.000685,42.540855,...,2.004744,0.902741,2.751060,3.096099,2.393896,2.482693,0.709030,1.467793,2.787167,2.457133
8,33.659309,36.322815,29.523591,29.791465,31.075888,33.659309,36.322815,29.523591,29.791465,31.075888,...,0.358559,1.098631,1.786610,0.374013,0.602337,0.326556,1.162750,1.915179,0.131881,0.373151
9,39.047702,36.495602,30.742514,33.057669,35.660226,39.047702,36.495602,30.742514,33.057669,35.660226,...,189.196619,12.546570,35.708215,140.076232,2.963565,68.787768,4.621833,5.946538,27.301339,3.285700
10,49.793243,33.738631,31.510737,30.161660,47.479766,49.793243,33.738631,31.510737,30.161660,47.479766,...,1.557620,0.035090,0.487963,0.000139,5889.579656,1.557620,0.035090,0.487963,0.000139,5889.579656

In [10]:
adhd_Low_beta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['Low_beta']])
df = df.T
df.index=[7]
adhd_Low_beta = adhd_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['Low_beta']])
df = df.T
df.index=[8]
adhd_Low_beta = adhd_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['Low_beta']])
df = df.T
df.index=[9]
adhd_Low_beta = adhd_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['Low_beta']])
df = df.T
df.index=[10]
adhd_Low_beta = adhd_Low_beta.append(df)


adhd_Low_beta = adhd_Low_beta.dropna(axis=1)   # column
adhd_Low_beta


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,33.950422,31.797823,21.254120,21.691576,26.807940,33.950422,31.797823,21.254120,21.691576,26.807940,...,5.781034,1.058400,9.371538,4.483000,5.982883,1.330243,0.437661,2.299296,5.053997,1.236149
8,19.587667,22.754131,14.705730,15.520577,18.796242,19.587667,22.754131,14.705730,15.520577,18.796242,...,0.436407,0.341151,0.769232,0.159820,0.409288,0.185311,0.307056,1.117154,0.116386,0.297666
9,22.137353,18.892065,15.531881,19.287202,21.333401,22.137353,18.892065,15.531881,19.287202,21.333401,...,110.815441,8.460333,25.180525,81.577541,2.378745,41.914623,7.132071,4.315505,16.212358,3.047198
10,25.211097,16.638091,14.815729,15.220018,22.568930,25.211097,16.638091,14.815729,15.220018,22.568930,...,1.537437,0.025320,0.756180,0.000198,5342.834004,1.537437,0.025320,0.756180,0.000198,5342.834004

In [11]:
adhd_High_beta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['High_beta']])
df = df.T
df.index=[7]
adhd_High_beta = adhd_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['High_beta']])
df = df.T
df.index=[8]
adhd_High_beta = adhd_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['High_beta']])
df = df.T
df.index=[9]
adhd_High_beta = adhd_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['High_beta']])
df = df.T
df.index=[10]
adhd_High_beta = adhd_High_beta.append(df)


adhd_High_beta = adhd_High_beta.dropna(axis=1)   # column
adhd_High_beta


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,25.645022,18.833161,13.090643,14.378104,18.032869,25.645022,18.833161,13.090643,14.378104,18.032869,...,6.485347,2.016485,7.453448,5.679804,6.167003,6.100508,0.732227,6.871618,7.118662,5.870472
8,12.902263,14.538209,6.877063,7.708580,12.252763,12.902263,14.538209,6.877063,7.708580,12.252763,...,0.152958,0.166119,0.321846,0.103042,0.237238,0.157253,0.175106,0.372157,0.077859,0.223327
9,13.735533,9.017299,6.948268,7.916308,13.846700,13.735533,9.017299,6.948268,7.916308,13.846700,...,101.515409,12.613029,17.396646,45.975959,1.553252,19.683287,3.807767,3.306334,9.845235,0.950930
10,18.101156,8.119806,7.608345,7.309842,15.540249,18.101156,8.119806,7.608345,7.309842,15.540249,...,1.090391,0.026989,0.385732,0.000278,2136.192703,1.090391,0.026989,0.385732,0.000278,2136.192703

In [12]:
adhd_Gamma = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['Gamma ']])
df = df.T
df.index=[7]
adhd_Gamma = adhd_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['Gamma ']])
df = df.T
df.index=[8]
adhd_Gamma = adhd_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['Gamma ']])
df = df.T
df.index=[9]
adhd_Gamma = adhd_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['Gamma ']])
df = df.T
df.index=[10]
adhd_Gamma = adhd_Gamma.append(df)


adhd_Gamma = adhd_Gamma.dropna(axis=1)   # column
adhd_Gamma


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,17.375215,12.683386,4.860802,14.551685,9.527630,17.375215,12.683386,4.860802,14.551685,9.527630,...,6.891009,3.338660,5.482985,17.276833,6.643182,7.003102,3.735210,4.389217,18.497012,6.654876
8,8.984602,9.748485,2.340716,3.241933,8.340695,8.984602,9.748485,2.340716,3.241933,8.340695,...,0.063114,0.066659,0.103191,0.025847,0.075149,0.054583,0.063767,0.133893,0.023008,0.069099
9,9.866776,2.884397,2.271384,2.457721,9.565298,9.866776,2.884397,2.271384,2.457721,9.565298,...,27.138984,5.146872,8.368728,12.799398,0.703750,5.494081,3.325755,1.746855,3.239867,0.324547
10,14.258715,2.669197,2.232271,2.613961,11.705482,14.258715,2.669197,2.232271,2.613961,11.705482,...,0.475334,0.019257,0.302837,0.000143,823.356487,0.475334,0.019257,0.302837,0.000143,823.356487

In [13]:
adhd_y = pd.Series([1]*len(adhd_Gamma))
adhd_y.index = adhd_Gamma.index
adhd_y

7     1
8     1
9     1
10    1
dtype: int64

- split train and test set

In [18]:
# Theta
train_control_Theta = control_Theta[:4]
train_adhd_Theta = adhd_Theta[:3]
train_Theta = train_control_Theta.append(train_adhd_Theta)

test_control_Theta = control_Theta[4:]
test_adhd_Theta = adhd_Theta[3:]
test_Theta = test_control_Theta.append(test_adhd_Theta)


# Alpha
train_control_Alpha = control_Alpha[:4]
train_adhd_Alpha = adhd_Alpha[:3]
train_Alpha = train_control_Alpha.append(train_adhd_Alpha)

test_control_Alpha = control_Alpha[4:]
test_adhd_Alpha = adhd_Alpha[3:]
test_Alpha = test_control_Alpha.append(test_adhd_Alpha)


# Low_beta
train_control_Low_beta = control_Low_beta[:4]
train_adhd_Low_beta = adhd_Low_beta[:3]
train_Low_beta = train_control_Low_beta.append(train_adhd_Low_beta)

test_control_Low_beta = control_Low_beta[4:]
test_adhd_Low_beta = adhd_Low_beta[3:]
test_Low_beta = test_control_Low_beta.append(test_adhd_Low_beta)


# High_beta
train_control_High_beta = control_High_beta[:4]
train_adhd_High_beta = adhd_High_beta[:3]
train_High_beta = train_control_High_beta.append(train_adhd_High_beta)

test_control_High_beta = control_High_beta[4:]
test_adhd_High_beta = adhd_High_beta[3:]
test_High_beta = test_control_High_beta.append(test_adhd_High_beta)


# Gamma
train_control_Gamma = control_Gamma[:4]
train_adhd_Gamma = adhd_Gamma[:3]
train_Gamma = train_control_Gamma.append(train_adhd_Gamma)

test_control_Gamma = control_Gamma[4:]
test_adhd_Gamma = adhd_Gamma[3:]
test_Gamma = test_control_Gamma.append(test_adhd_Gamma)




# y
train_y = control_y[:4].append(adhd_y[:3])
test_y = control_y[4:].append(adhd_y[3:])

In [19]:
from keras import layers, models
from tensorflow.keras.layers import SimpleRNN, Input, Dense, concatenate, LSTM
from tensorflow.keras.models import Sequential, Model

# Theta
Theta_input = Input(shape=(490,1))
Theta_output =Dense(256, activation='relu')(Theta_input)
Theta_output =LSTM(256)(Theta_output)
Theta_output =Dense(256, activation='relu')(Theta_output)
Theta_model = Model(inputs = Theta_input, outputs = Theta_output)


# Alpha
Alpha_input = Input(shape=(490,1))
Alpha_output = Dense(256, activation='relu')(Alpha_input)
Alpha_output = LSTM(256)(Alpha_output)
Alpha_output = Dense(256, activation='relu')(Alpha_output)
Alpha_model = Model(inputs = Alpha_input, outputs = Alpha_output)


# Low_beta
Low_beta_input = Input(shape=(490,1))
Low_beta_output = Dense(256, activation='relu')(Low_beta_input)
Low_beta_output = LSTM(256)(Low_beta_output)
Low_beta_output = Dense(256, activation='relu')(Low_beta_output)
Low_beta_model = Model(inputs = Low_beta_input, outputs = Low_beta_output)


# High_beta
High_beta_input = Input(shape=(490,1))
High_beta_output = Dense(256, activation='relu')(High_beta_input)
High_beta_output = LSTM(256)(High_beta_output)
High_beta_output = Dense(256, activation='relu')(High_beta_output)
High_beta_model = Model(inputs = High_beta_input, outputs = High_beta_output)


# Gamma
Gamma_input = Input(shape=(490,1))
Gamma_output = Dense(256, activation='relu')(Gamma_input)
Gamma_output = LSTM(256)(Gamma_output)
Gamma_output = Dense(256, activation='relu')(Gamma_output)
Gamma_model = Model(inputs = Gamma_input, outputs = Gamma_output)





concatenated = concatenate([Theta_model.output, Alpha_model.output, 
                           Low_beta_model.output, High_beta_model.output, 
                           Gamma_model.output])
concatenated = Dense(256, activation='relu')(concatenated)
concatenated = Dense(256, activation='relu')(concatenated)
concat_out = Dense(1, activation='sigmoid')(concatenated)

concat_model = Model([Theta_input, Alpha_input, 
                     Low_beta_input, High_beta_input, 
                    Gamma_input], concat_out)
concat_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = concat_model.fit([train_Theta, train_Alpha, 
                           train_Low_beta, train_High_beta, 
                            train_Gamma], train_y, epochs=10, batch_size=32)

Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6955 - accuracy: 0.5714
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5931 - accuracy: 0.4286
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5470 - accuracy: 0.4286
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 0.5031 - accuracy: 0.7143
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4573 - accuracy: 0.8571
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4108 - accuracy: 0.8571
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 0.3637 - accuracy: 0.8571
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 0.3429 - accuracy: 0.8571
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 0.3430 - accuracy: 0.8571
Epoch 10/10
1/1 [==============================] - 0s 997us/step - loss: 0.3087 - accuracy: 0.8571

In [20]:
print("\n 테스트 정확도: %.4f" % (concat_model.evaluate([test_Theta, test_Alpha, 
                                                  test_Low_beta, test_High_beta, 
                                                    test_Gamma], test_y)[1]))

1/1 [==============================] - 0s 997us/step - loss: 0.1572 - accuracy: 1.0000

 테스트 정확도: 1.0000

In [21]:
concat_model.save("lstm_model_adults_keyboard.h5")

# theta/beta 추가

In [37]:
control_Theta_per_Lbeta = control_Theta.copy()   # Theta / Low_beta

rows = control_Theta_per_Lbeta.index
cols = control_Theta_per_Lbeta.columns

for row in rows:
    for col in cols:
        control_Theta_per_Lbeta.loc[row, col] = control_Theta_per_Lbeta.loc[row, col] / control_Low_beta.loc[row, col]
control_Theta_per_Lbeta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
1,4.844235,5.235813,1.884977,0.542236,6.628322,4.844235,5.235813,1.884977,0.542236,6.628322,...,1.685235,2.082292,0.697385,1.639223,4.090704,1.685235,2.082292,0.697385,1.639223,4.090704
2,7.700800,5.486774,2.792331,10.806348,5.254303,7.700800,5.486774,2.792331,10.806348,5.254303,...,3.248426,1.236617,0.415505,2.228351,2.688836,3.248426,1.236617,0.415505,2.228351,2.688836
3,6.368956,1.476295,2.657769,0.824495,5.494977,6.368956,1.476295,2.657769,0.824495,5.494977,...,2.836103,1.552155,1.748394,0.749221,2.445620,1.012543,1.152686,1.541420,1.132691,2.059454
4,0.437466,0.896729,1.624977,0.729689,1.758352,0.437466,0.896729,1.624977,0.729689,1.758352,...,4.402476,0.183641,2.740385,0.594543,2.253699,4.402476,0.183641,2.740385,0.594543,2.253699
5,12.401077,0.584193,6.462267,6.173793,3.324887,12.401077,0.584193,6.462267,6.173793,3.324887,...,2.154920,3.764023,1.752320,2.160888,4.030412,2.154920,3.764023,1.752320,2.160888,4.030412

In [38]:
control_Theta_per_Hbeta = control_Theta.copy()   # Theta / High_beta

rows = control_Theta_per_Lbeta.index
cols = control_Theta_per_Lbeta.columns

for row in rows:
    for col in cols:
        control_Theta_per_Hbeta.loc[row, col] = control_Theta_per_Hbeta.loc[row, col] / control_High_beta.loc[row, col]
control_Theta_per_Hbeta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
1,2.895451,5.395683,4.473459,1.209489,3.300133,2.895451,5.395683,4.473459,1.209489,3.300133,...,3.270776,1.396189,3.970097,1.532429,5.882509,3.270776,1.396189,3.970097,1.532429,5.882509
2,6.744443,12.977469,2.977008,17.175819,7.406627,6.744443,12.977469,2.977008,17.175819,7.406627,...,7.417287,2.521013,1.376286,3.383217,8.325896,7.417287,2.521013,1.376286,3.383217,8.325896
3,7.265056,0.805496,2.637324,0.906471,7.303818,7.265056,0.805496,2.637324,0.906471,7.303818,...,8.465397,1.076088,2.663804,0.693738,5.542998,2.711534,0.390846,1.923105,0.941966,3.068680
4,0.879710,0.237830,1.351808,0.496333,2.232350,0.879710,0.237830,1.351808,0.496333,2.232350,...,6.077530,0.498657,1.713477,0.907597,4.112483,6.077530,0.498657,1.713477,0.907597,4.112483
5,17.728769,1.139589,12.118847,9.343608,3.527472,17.728769,1.139589,12.118847,9.343608,3.527472,...,3.368452,4.990894,2.316109,4.295737,3.129279,3.368452,4.990894,2.316109,4.295737,3.129279

In [39]:
adhd_Theta_per_Lbeta = adhd_Theta.copy()   # Theta / Low_beta

rows = adhd_Theta_per_Lbeta.index
cols = adhd_Theta_per_Lbeta.columns

for row in rows:
    for col in cols:
        adhd_Theta_per_Lbeta.loc[row, col] = adhd_Theta_per_Lbeta.loc[row, col] / adhd_Low_beta.loc[row, col]
adhd_Theta_per_Lbeta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,4.244147,5.162687,6.884358,6.240471,5.236981,4.244147,5.162687,6.884358,6.240471,5.236981,...,0.616350,0.974115,0.377400,0.283042,0.686508,1.108701,0.835916,1.234569,0.249066,1.692684
8,4.622000,4.335531,6.281894,5.516026,4.471989,4.622000,4.335531,6.281894,5.516026,4.471989,...,2.187423,2.637752,8.990617,1.235250,1.969568,5.205973,1.329878,3.211546,1.120531,3.131396
9,5.310961,5.310757,5.421902,4.674587,4.414658,5.310961,5.310757,5.421902,4.674587,4.414658,...,17.898222,5.280793,1.846807,8.091329,1.824723,15.358897,1.615991,2.788573,9.872851,4.509285
10,8.068496,5.960885,6.161362,5.646724,8.494823,8.068496,5.960885,6.161362,5.646724,8.494823,...,1.404439,6.013161,0.961404,0.470738,1.472448,1.404439,6.013161,0.961404,0.470738,1.472448

In [40]:
adhd_Theta_per_Hbeta = adhd_Theta.copy()   # Theta / High_beta

rows = adhd_Theta_per_Hbeta.index
cols = adhd_Theta_per_Hbeta.columns

for row in rows:
    for col in cols:
        adhd_Theta_per_Hbeta.loc[row, col] = adhd_Theta_per_Hbeta.loc[row, col] / adhd_High_beta.loc[row, col]
adhd_Theta_per_Hbeta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,5.618656,8.716657,11.177524,9.414707,7.785376,5.618656,8.716657,11.177524,9.414707,7.785376,...,0.549414,0.511288,0.474521,0.223402,0.666012,0.241757,0.499638,0.413096,0.176828,0.356430
8,7.016923,6.785653,13.433036,11.106054,6.860214,7.016923,6.785653,13.433036,11.106054,6.860214,...,6.240961,5.417030,21.488160,1.915898,3.397939,6.134855,2.331995,9.640536,1.674994,4.173753
9,8.559596,11.126521,12.119903,11.389109,6.801596,8.559596,11.126521,12.119903,11.389109,6.801596,...,19.537915,3.542152,2.673134,14.356867,2.794493,32.706039,3.026804,3.639711,16.257833,14.449737
10,11.237715,12.214300,11.998019,11.757195,12.336937,11.237715,12.214300,11.998019,11.757195,12.336937,...,1.980240,5.641275,1.884713,0.336162,3.682741,1.980240,5.641275,1.884713,0.336162,3.682741

# theta/beta 추가한 model train

- split train and test set

In [41]:
# Theta
train_control_Theta = control_Theta[:4]
train_adhd_Theta = adhd_Theta[:3]
train_Theta = train_control_Theta.append(train_adhd_Theta)

test_control_Theta = control_Theta[4:]
test_adhd_Theta = adhd_Theta[3:]
test_Theta = test_control_Theta.append(test_adhd_Theta)


# Alpha
train_control_Alpha = control_Alpha[:4]
train_adhd_Alpha = adhd_Alpha[:3]
train_Alpha = train_control_Alpha.append(train_adhd_Alpha)

test_control_Alpha = control_Alpha[4:]
test_adhd_Alpha = adhd_Alpha[3:]
test_Alpha = test_control_Alpha.append(test_adhd_Alpha)


# Low_beta
train_control_Low_beta = control_Low_beta[:4]
train_adhd_Low_beta = adhd_Low_beta[:3]
train_Low_beta = train_control_Low_beta.append(train_adhd_Low_beta)

test_control_Low_beta = control_Low_beta[4:]
test_adhd_Low_beta = adhd_Low_beta[3:]
test_Low_beta = test_control_Low_beta.append(test_adhd_Low_beta)


# High_beta
train_control_High_beta = control_High_beta[:4]
train_adhd_High_beta = adhd_High_beta[:3]
train_High_beta = train_control_High_beta.append(train_adhd_High_beta)

test_control_High_beta = control_High_beta[4:]
test_adhd_High_beta = adhd_High_beta[3:]
test_High_beta = test_control_High_beta.append(test_adhd_High_beta)


# Gamma
train_control_Gamma = control_Gamma[:4]
train_adhd_Gamma = adhd_Gamma[:3]
train_Gamma = train_control_Gamma.append(train_adhd_Gamma)

test_control_Gamma = control_Gamma[4:]
test_adhd_Gamma = adhd_Gamma[3:]
test_Gamma = test_control_Gamma.append(test_adhd_Gamma)

# Theta_per_Lbeta
train_control_Theta_per_Lbeta = control_Theta_per_Lbeta[:4]
train_adhd_Theta_per_Lbeta = adhd_Theta_per_Lbeta[:3]
train_Theta_per_Lbeta = train_control_Theta_per_Lbeta.append(train_adhd_Theta_per_Lbeta)

test_control_Theta_per_Lbeta = control_Theta_per_Lbeta[4:]
test_adhd_Theta_per_Lbeta = adhd_Theta_per_Lbeta[3:]
test_Theta_per_Lbeta = test_control_Theta_per_Lbeta.append(test_adhd_Theta_per_Lbeta)


# Theta_per_Hbeta
train_control_Theta_per_Hbeta = control_Theta_per_Hbeta[:4]
train_adhd_Theta_per_Hbeta = adhd_Theta_per_Hbeta[:3]
train_Theta_per_Hbeta = train_control_Theta_per_Hbeta.append(train_adhd_Theta_per_Hbeta)

test_control_Theta_per_Hbeta = control_Theta_per_Hbeta[4:]
test_adhd_Theta_per_Hbeta = adhd_Theta_per_Hbeta[3:]
test_Theta_per_Hbeta = test_control_Theta_per_Hbeta.append(test_adhd_Theta_per_Hbeta)


# y
train_y = control_y[:4].append(adhd_y[:3])
test_y = control_y[4:].append(adhd_y[3:])

- lstm

In [42]:
from keras import layers, models
from tensorflow.keras.layers import SimpleRNN, Input, Dense, concatenate, LSTM
from tensorflow.keras.models import Sequential, Model

# Theta
Theta_input = Input(shape=(490,1))
Theta_output =Dense(256, activation='relu')(Theta_input)
Theta_output =LSTM(256)(Theta_output)
Theta_output =Dense(256, activation='relu')(Theta_output)
Theta_model = Model(inputs = Theta_input, outputs = Theta_output)


# Alpha
Alpha_input = Input(shape=(490,1))
Alpha_output = Dense(256, activation='relu')(Alpha_input)
Alpha_output = LSTM(256)(Alpha_output)
Alpha_output = Dense(256, activation='relu')(Alpha_output)
Alpha_model = Model(inputs = Alpha_input, outputs = Alpha_output)


# Low_beta
Low_beta_input = Input(shape=(490,1))
Low_beta_output = Dense(256, activation='relu')(Low_beta_input)
Low_beta_output = LSTM(256)(Low_beta_output)
Low_beta_output = Dense(256, activation='relu')(Low_beta_output)
Low_beta_model = Model(inputs = Low_beta_input, outputs = Low_beta_output)


# High_beta
High_beta_input = Input(shape=(490,1))
High_beta_output = Dense(256, activation='relu')(High_beta_input)
High_beta_output = LSTM(256)(High_beta_output)
High_beta_output = Dense(256, activation='relu')(High_beta_output)
High_beta_model = Model(inputs = High_beta_input, outputs = High_beta_output)


# Gamma
Gamma_input = Input(shape=(490,1))
Gamma_output = Dense(256, activation='relu')(Gamma_input)
Gamma_output = LSTM(256)(Gamma_output)
Gamma_output = Dense(256, activation='relu')(Gamma_output)
Gamma_model = Model(inputs = Gamma_input, outputs = Gamma_output)


# Theta_per_Lbeta
Theta_per_Lbeta_input = Input(shape=(490,1))
Theta_per_Lbeta_output = Dense(256, activation='relu')(Theta_per_Lbeta_input)
Theta_per_Lbeta_output = LSTM(256)(Theta_per_Lbeta_output)
Theta_per_Lbeta_output = Dense(256, activation='relu')(Theta_per_Lbeta_output)
Theta_per_Lbeta_model = Model(inputs = Theta_per_Lbeta_input, outputs = Theta_per_Lbeta_output)

# Theta_per_Hbeta
Theta_per_Hbeta_input = Input(shape=(490,1))
Theta_per_Hbeta_output = Dense(256, activation='relu')(Theta_per_Hbeta_input)
Theta_per_Hbeta_output = LSTM(256)(Theta_per_Hbeta_output)
Theta_per_Hbeta_output = Dense(256, activation='relu')(Theta_per_Hbeta_output)
Theta_per_Hbeta_model = Model(inputs = Theta_per_Hbeta_input, outputs = Theta_per_Hbeta_output)


concatenated = concatenate([Theta_model.output, Alpha_model.output, 
                           Low_beta_model.output, High_beta_model.output, 
                           Gamma_model.output, 
                           Theta_per_Lbeta_model.output, Theta_per_Hbeta_model.output])
concatenated = Dense(256, activation='relu')(concatenated)
concatenated = Dense(256, activation='relu')(concatenated)
concat_out = Dense(1, activation='sigmoid')(concatenated)

concat_model = Model([Theta_input, Alpha_input, 
                     Low_beta_input, High_beta_input, 
                    Gamma_input, 
                     Theta_per_Lbeta_input, Theta_per_Hbeta_input], concat_out)
concat_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = concat_model.fit([train_Theta, train_Alpha, 
                           train_Low_beta, train_High_beta, 
                            train_Gamma, 
                           train_Theta_per_Lbeta, train_Theta_per_Hbeta], train_y, epochs=6, batch_size=32)

# concat_model.save("lstm_model_adults")

Epoch 1/6
1/1 [==============================] - 0s 2ms/step - loss: 0.6786 - accuracy: 0.7143
Epoch 2/6
1/1 [==============================] - 0s 2ms/step - loss: 0.5700 - accuracy: 0.5714
Epoch 3/6
1/1 [==============================] - 0s 2ms/step - loss: 0.4700 - accuracy: 0.8571
Epoch 4/6
1/1 [==============================] - 0s 2ms/step - loss: 0.4089 - accuracy: 0.8571
Epoch 5/6
1/1 [==============================] - 0s 2ms/step - loss: 0.3935 - accuracy: 0.8571
Epoch 6/6
1/1 [==============================] - 0s 997us/step - loss: 0.3587 - accuracy: 0.8571

In [43]:
print("\n 테스트 정확도: %.4f" % (concat_model.evaluate([test_Theta, test_Alpha, 
                                                  test_Low_beta, test_High_beta, 
                                                    test_Gamma, 
                                                  test_Theta_per_Lbeta, test_Theta_per_Hbeta], test_y)[1]))

1/1 [==============================] - 0s 2ms/step - loss: 0.1414 - accuracy: 1.0000

 테스트 정확도: 1.0000

In [44]:
concat_model.save("lstm_model_adults_keyboard_extend.h5")

# emotive model test using keyboard dataset

In [67]:
from keras.models import load_model

model = load_model("lstm_model_adults.h5")

In [68]:
len(control_y)

5

In [47]:
print("\n 테스트 정확도: %.4f" % (model.evaluate([control_Theta, control_Alpha, 
                                                  control_Low_beta, control_High_beta, 
                                                    control_Gamma], control_y)[1]))

WARNING: Logging before flag parsing goes to stderr.
W0205 14:53:25.316103 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_71:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:25.319095 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_72:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:25.322089 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_73:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:25.324082 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_74:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:25.329070 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_75:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:27.210937 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_71:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:27.216894 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_72:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:27.220899 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_73:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:27.224874 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_74:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 14:53:27.227896 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_75:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).

1/1 [==============================] - 0s 2ms/step - loss: 0.5842 - accuracy: 1.0000

 테스트 정확도: 1.0000

In [48]:
len(adhd_y)

4

In [49]:
print("\n 테스트 정확도: %.4f" % (model.evaluate([adhd_Theta, adhd_Alpha, 
                                                  adhd_Low_beta, adhd_High_beta, 
                                                    adhd_Gamma], adhd_y)[1]))

1/1 [==============================] - 0s 2ms/step - loss: 0.3225 - accuracy: 0.7500

 테스트 정확도: 0.7500

- extend model

In [69]:
model = load_model("lstm_model_adults_emotive_extend.h5")

In [70]:
print("\n 테스트 정확도: %.4f" % (model.evaluate([control_Theta, control_Alpha, 
                                                  control_Low_beta, control_High_beta, 
                                                    control_Gamma, 
                                            control_Theta_per_Lbeta, control_Theta_per_Hbeta], control_y)[1]))

W0205 15:13:27.408533 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_125:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:27.413520 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_126:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:27.417510 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_127:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:27.420501 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_128:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:27.424491 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_129:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:27.430474 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_130:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:27.434463 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_131:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:29.399797 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_125:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:29.401790 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_126:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:29.404783 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_127:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:29.407784 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_128:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:29.409770 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_129:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:29.412763 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_130:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 15:13:29.415755 31960 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_131:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).

1/1 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 1.0000

 테스트 정확도: 1.0000

In [71]:
print("\n 테스트 정확도: %.4f" % (model.evaluate([adhd_Theta, adhd_Alpha, 
                                                  adhd_Low_beta, adhd_High_beta, 
                                                    adhd_Gamma,
                                           adhd_Theta_per_Lbeta, adhd_Theta_per_Hbeta], adhd_y)[1]))

1/1 [==============================] - 0s 2ms/step - loss: 0.4107 - accuracy: 0.7500

 테스트 정확도: 0.7500