In [2]:
import pandas as pd
import numpy as np

train: control(1,2,3,4)+adhd(7,8,9)


test: control(5)+adhd(10)

- Control dataset

In [22]:
control_Theta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['Theta']])
df = df.T
df.index=[1]
control_Theta = control_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['Theta']])
df = df.T
df.index=[2]
control_Theta= control_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['Theta']])
df = df.T
df.index=[3]
control_Theta= control_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['Theta']])
df = df.T
df.index=[4]
control_Theta= control_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['Theta']])
df = df.T
df.index=[5]
control_Theta= control_Theta.append(df)



control_Theta = control_Theta.dropna(axis=1)   # column
control_Theta


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094
1,0.332158,0.642957,0.458338,0.528602,0.683617,0.332158,0.642957,0.458338,0.528602,0.683617,...,0.723373,0.478064,0.204944,0.152939,2.614993,0.723373,0.478064,0.204944,0.152939,2.614993
2,2.857617,1.294798,1.600999,7.868133,2.315394,2.857617,1.294798,1.600999,7.868133,2.315394,...,1.580422,0.314821,0.495913,1.160829,1.611493,1.580422,0.314821,0.495913,1.160829,1.611493
3,1.191336,0.528186,0.798593,0.498767,1.283596,1.191336,0.528186,0.798593,0.498767,1.283596,...,1.206690,0.545619,0.606821,0.793787,1.486391,1.206690,0.545619,0.606821,0.793787,1.486391
4,0.420250,0.346276,0.272355,0.827547,1.578074,0.420250,0.346276,0.272355,0.827547,1.578074,...,0.912445,0.365741,0.408474,1.070957,0.685877,0.912445,0.365741,0.408474,1.070957,0.685877
5,4.380045,0.371932,1.221854,2.046963,2.241406,4.380045,0.371932,1.221854,2.046963,2.241406,...,1.468484,0.218398,0.073481,0.925895,2.269883,2.626259,0.355987,0.329180,1.591380,2.730385

In [24]:
control_Alpha = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[1]
control_Alpha = control_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[2]
control_Alpha= control_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[3]
control_Alpha= control_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[4]
control_Alpha= control_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['Alpha']])
df = df.T
df.index=[5]
control_Alpha= control_Alpha.append(df)



control_Alpha = control_Alpha.dropna(axis=1)   # column
control_Alpha

,0,1,2,3,4,5,6,7,8,9,...,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094
1,0.175801,0.259134,0.685974,0.753501,0.293142,0.175801,0.259134,0.685974,0.753501,0.293142,...,0.422871,0.236050,0.291517,0.496246,1.100500,0.422871,0.236050,0.291517,0.496246,1.100500
2,0.347631,0.368325,1.816854,1.742926,0.350514,0.347631,0.368325,1.816854,1.742926,0.350514,...,0.732518,0.282051,0.701667,0.908093,0.746108,0.732518,0.282051,0.701667,0.908093,0.746108
3,0.630867,0.305691,0.777314,1.300691,0.633542,0.630867,0.305691,0.777314,1.300691,0.633542,...,0.366703,0.533108,0.364620,1.084269,0.624368,0.366703,0.533108,0.364620,1.084269,0.624368
4,0.495860,0.514494,0.426581,2.019397,1.612966,0.495860,0.514494,0.426581,2.019397,1.612966,...,1.224033,0.591915,0.794061,1.868449,2.243455,1.224033,0.591915,0.794061,1.868449,2.243455
5,0.660897,1.067346,0.227851,1.530523,0.926018,0.660897,1.067346,0.227851,1.530523,0.926018,...,0.763249,0.158079,0.299422,1.406839,1.526217,0.408820,0.153091,0.317695,0.822739,0.837228

In [25]:
control_Low_beta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['Low_beta']])
df = df.head(1225).T
df.index=[1]
control_Low_beta = control_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['Low_beta']])
df = df.T
df.index=[2]
control_Low_beta= control_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['Low_beta']])
df = df.T
df.index=[3]
control_Low_beta= control_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['Low_beta']])
df = df.T
df.index=[4]
control_Low_beta= control_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['Low_beta']])
df = df.T
df.index=[5]
control_Low_beta= control_Low_beta.append(df)



control_Low_beta = control_Low_beta.dropna(axis=1)   # column
control_Low_beta

,0,1,2,3,4,5,6,7,8,9,...,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094
1,0.068568,0.122800,0.243153,0.974857,0.103136,0.068568,0.122800,0.243153,0.974857,0.103136,...,0.327168,0.273438,0.309720,0.832399,1.021544,0.327168,0.273438,0.309720,0.832399,1.021544
2,0.371081,0.235985,0.573356,0.728103,0.440666,0.371081,0.235985,0.573356,0.728103,0.440666,...,0.452554,0.221223,1.278607,0.836441,0.627042,0.452554,0.221223,1.278607,0.836441,0.627042
3,0.187054,0.357778,0.300475,0.604936,0.233595,0.187054,0.357778,0.300475,0.604936,0.233595,...,0.250381,0.276057,0.627599,0.716910,0.245287,0.250381,0.276057,0.627599,0.716910,0.245287
4,0.960645,0.386155,0.167605,1.134109,0.897473,0.960645,0.386155,0.167605,1.134109,0.897473,...,0.282140,2.107945,0.270326,0.856889,0.431425,0.282140,2.107945,0.270326,0.856889,0.431425
5,0.353199,0.636659,0.189075,0.331557,0.674130,0.353199,0.636659,0.189075,0.331557,0.674130,...,0.693954,0.190011,0.455509,1.001421,0.785198,0.254495,0.114918,0.314298,0.341820,0.421368

In [41]:
control_High_beta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['High_beta']])
df = df.head(1225).T
df.index=[1]
control_High_beta = control_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['High_beta']])
df = df.T
df.index=[2]
control_High_beta= control_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['High_beta']])
df = df.T
df.index=[3]
control_High_beta= control_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['High_beta']])
df = df.T
df.index=[4]
control_High_beta= control_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['High_beta']])
df = df.T
df.index=[5]
control_High_beta= control_High_beta.append(df)



control_High_beta = control_High_beta.dropna(axis=1)   # column
control_High_beta

,0,1,2,3,4,5,6,7,8,9,...,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094
1,0.114717,0.119161,0.102457,0.437046,0.207148,0.114717,0.119161,0.102457,0.437046,0.207148,...,0.139316,0.131617,0.152403,0.602601,0.311874,0.139316,0.131617,0.152403,0.602601,0.311874
2,0.423699,0.099773,0.537788,0.458094,0.312611,0.423699,0.099773,0.537788,0.458094,0.312611,...,0.257802,0.142728,0.646773,0.315435,0.257315,0.257802,0.142728,0.646773,0.315435,0.257315
3,0.163982,0.655728,0.302804,0.550229,0.175743,0.163982,0.655728,0.302804,0.550229,0.175743,...,0.221266,1.832248,0.393875,0.894600,0.338533,0.221266,1.832248,0.393875,0.894600,0.338533
4,0.477714,1.455983,0.201474,1.667320,0.706912,0.477714,1.455983,0.201474,1.667320,0.706912,...,0.140272,1.647356,0.163586,1.144457,0.224280,0.140272,1.647356,0.163586,1.144457,0.224280
5,0.247059,0.326374,0.100823,0.219076,0.635414,0.247059,0.326374,0.100823,0.219076,0.635414,...,0.523441,0.163218,0.288976,0.570745,0.526892,0.342307,0.110304,0.294529,0.265113,0.296182

In [26]:
control_Gamma = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/1/abdul_keyboard5.csv')[['Gamma ']])
df = df.head(1225).T
df.index=[1]
control_Gamma = control_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/2/alaa_keyboard5.csv')[['Gamma ']])
df = df.T
df.index=[2]
control_Gamma= control_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/3/ali_keyboard5.csv')[['Gamma ']])
df = df.T
df.index=[3]
control_Gamma= control_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/4/amer_keyboard5.csv')[['Gamma ']])
df = df.T
df.index=[4]
control_Gamma= control_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/Control/5/sharno_keyboard5.csv')[['Gamma ']])
df = df.T
df.index=[5]
control_Gamma= control_Gamma.append(df)



control_Gamma = control_Gamma.dropna(axis=1)   # column
control_Gamma

,0,1,2,3,4,5,6,7,8,9,...,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094
1,0.073143,0.083767,0.073224,0.104580,0.071107,0.073143,0.083767,0.073224,0.104580,0.071107,...,0.060612,0.128931,0.095482,0.325420,0.084902,0.060612,0.128931,0.095482,0.325420,0.084902
2,0.117245,0.105164,0.252184,0.189314,0.166669,0.117245,0.105164,0.252184,0.189314,0.166669,...,0.154777,0.096480,0.407248,0.144021,0.169949,0.154777,0.096480,0.407248,0.144021,0.169949
3,0.144762,0.480914,0.113822,0.591946,0.155756,0.144762,0.480914,0.113822,0.591946,0.155756,...,0.096853,0.685934,0.300811,0.839521,0.202688,0.096853,0.685934,0.300811,0.839521,0.202688
4,0.310296,2.125887,0.116311,0.702569,0.351376,0.310296,2.125887,0.116311,0.702569,0.351376,...,0.164589,1.138712,0.148562,0.396724,0.179012,0.164589,1.138712,0.148562,0.396724,0.179012
5,0.101996,0.353386,0.095654,0.113603,0.142634,0.101996,0.353386,0.095654,0.113603,0.142634,...,0.104807,0.093976,0.096069,0.078816,0.212894,0.127753,0.105217,0.108564,0.087923,0.230712

In [27]:
control_y = pd.Series([0]*len(control_Gamma))
control_y.index = control_Gamma.index
control_y

1    0
2    0
3    0
4    0
5    0
dtype: int64

- adhd dataset

In [29]:
adhd_Theta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['Theta']])
df = df.T
df.index=[7]
adhd_Theta = adhd_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['Theta']])
df = df.T
df.index=[8]
adhd_Theta = adhd_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['Theta']])
df = df.T
df.index=[9]
adhd_Theta = adhd_Theta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['Theta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['Theta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['Theta']])
df = df.T
df.index=[10]
adhd_Theta = adhd_Theta.append(df)


adhd_Theta = adhd_Theta.dropna(axis=1)   # column
adhd_Theta


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,144.090564,164.162214,146.320972,135.365645,140.392667,144.090564,164.162214,146.320972,135.365645,140.392667,...,3.563141,1.031004,3.536819,1.268879,4.107299,1.474841,0.365848,2.838640,1.258778,2.092410
8,90.534190,98.651231,92.379840,85.611914,84.056584,90.534190,98.651231,92.379840,85.611914,84.056584,...,0.954606,0.899872,6.915874,0.197417,0.806120,0.964724,0.408348,3.587791,0.130414,0.932110
9,117.570611,100.331176,84.212331,90.159698,94.179666,117.570611,100.331176,84.212331,90.159698,94.179666,...,1983.399406,44.677269,46.503565,660.070717,4.340552,643.762352,11.525363,12.034101,160.062192,13.740685
10,203.415632,99.177751,91.285068,85.943236,191.719079,203.415632,99.177751,91.285068,85.943236,191.719079,...,2.159236,0.152251,0.726994,0.000093,7867.043400,2.159236,0.152251,0.726994,0.000093,7867.043400

In [30]:
adhd_Alpha = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['Alpha']])
df = df.T
df.index=[7]
adhd_Alpha = adhd_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['Alpha']])
df = df.T
df.index=[8]
adhd_Alpha = adhd_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['Alpha']])
df = df.T
df.index=[9]
adhd_Alpha = adhd_Alpha.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['Alpha']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['Alpha']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['Alpha']])
df = df.T
df.index=[10]
adhd_Alpha = adhd_Alpha.append(df)


adhd_Alpha = adhd_Alpha.dropna(axis=1)   # column
adhd_Alpha


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,47.345218,52.095417,41.021074,39.000685,42.540855,47.345218,52.095417,41.021074,39.000685,42.540855,...,2.004744,0.902741,2.751060,3.096099,2.393896,2.482693,0.709030,1.467793,2.787167,2.457133
8,33.659309,36.322815,29.523591,29.791465,31.075888,33.659309,36.322815,29.523591,29.791465,31.075888,...,0.358559,1.098631,1.786610,0.374013,0.602337,0.326556,1.162750,1.915179,0.131881,0.373151
9,39.047702,36.495602,30.742514,33.057669,35.660226,39.047702,36.495602,30.742514,33.057669,35.660226,...,189.196619,12.546570,35.708215,140.076232,2.963565,68.787768,4.621833,5.946538,27.301339,3.285700
10,49.793243,33.738631,31.510737,30.161660,47.479766,49.793243,33.738631,31.510737,30.161660,47.479766,...,1.557620,0.035090,0.487963,0.000139,5889.579656,1.557620,0.035090,0.487963,0.000139,5889.579656

In [36]:
adhd_Low_beta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['Low_beta']])
df = df.T
df.index=[7]
adhd_Low_beta = adhd_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['Low_beta']])
df = df.T
df.index=[8]
adhd_Low_beta = adhd_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['Low_beta']])
df = df.T
df.index=[9]
adhd_Low_beta = adhd_Low_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['Low_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['Low_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['Low_beta']])
df = df.T
df.index=[10]
adhd_Low_beta = adhd_Low_beta.append(df)


adhd_Low_beta = adhd_Low_beta.dropna(axis=1)   # column
adhd_Low_beta


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,33.950422,31.797823,21.254120,21.691576,26.807940,33.950422,31.797823,21.254120,21.691576,26.807940,...,5.781034,1.058400,9.371538,4.483000,5.982883,1.330243,0.437661,2.299296,5.053997,1.236149
8,19.587667,22.754131,14.705730,15.520577,18.796242,19.587667,22.754131,14.705730,15.520577,18.796242,...,0.436407,0.341151,0.769232,0.159820,0.409288,0.185311,0.307056,1.117154,0.116386,0.297666
9,22.137353,18.892065,15.531881,19.287202,21.333401,22.137353,18.892065,15.531881,19.287202,21.333401,...,110.815441,8.460333,25.180525,81.577541,2.378745,41.914623,7.132071,4.315505,16.212358,3.047198
10,25.211097,16.638091,14.815729,15.220018,22.568930,25.211097,16.638091,14.815729,15.220018,22.568930,...,1.537437,0.025320,0.756180,0.000198,5342.834004,1.537437,0.025320,0.756180,0.000198,5342.834004

In [37]:
adhd_High_beta = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['High_beta']])
df = df.T
df.index=[7]
adhd_High_beta = adhd_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['High_beta']])
df = df.T
df.index=[8]
adhd_High_beta = adhd_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['High_beta']])
df = df.T
df.index=[9]
adhd_High_beta = adhd_High_beta.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['High_beta']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['High_beta']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['High_beta']])
df = df.T
df.index=[10]
adhd_High_beta = adhd_High_beta.append(df)


adhd_High_beta = adhd_High_beta.dropna(axis=1)   # column
adhd_High_beta


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,25.645022,18.833161,13.090643,14.378104,18.032869,25.645022,18.833161,13.090643,14.378104,18.032869,...,6.485347,2.016485,7.453448,5.679804,6.167003,6.100508,0.732227,6.871618,7.118662,5.870472
8,12.902263,14.538209,6.877063,7.708580,12.252763,12.902263,14.538209,6.877063,7.708580,12.252763,...,0.152958,0.166119,0.321846,0.103042,0.237238,0.157253,0.175106,0.372157,0.077859,0.223327
9,13.735533,9.017299,6.948268,7.916308,13.846700,13.735533,9.017299,6.948268,7.916308,13.846700,...,101.515409,12.613029,17.396646,45.975959,1.553252,19.683287,3.807767,3.306334,9.845235,0.950930
10,18.101156,8.119806,7.608345,7.309842,15.540249,18.101156,8.119806,7.608345,7.309842,15.540249,...,1.090391,0.026989,0.385732,0.000278,2136.192703,1.090391,0.026989,0.385732,0.000278,2136.192703

In [38]:
adhd_Gamma = pd.DataFrame()

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/7/ayse nur key 5.csv')[['Gamma ']])
df = df.T
df.index=[7]
adhd_Gamma = adhd_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam Key 2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/8/Humam key 5.csv')[['Gamma ']])
df = df.T
df.index=[8]
adhd_Gamma = adhd_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/9/key said 5.csv')[['Gamma ']])
df = df.T
df.index=[9]
adhd_Gamma = adhd_Gamma.append(df)

df = pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 1.csv')[['Gamma ']]
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 2.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 3.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 4.csv')[['Gamma ']])
df.append(pd.read_csv('./Dataset_Adults_Keyboard/ADHD/10/key zeynep 5.csv')[['Gamma ']])
df = df.T
df.index=[10]
adhd_Gamma = adhd_Gamma.append(df)


adhd_Gamma = adhd_Gamma.dropna(axis=1)   # column
adhd_Gamma


# control_Theta.append(df)
# control_Theta

,0,1,2,3,4,5,6,7,8,9,...,480,481,482,483,484,485,486,487,488,489
7,17.375215,12.683386,4.860802,14.551685,9.527630,17.375215,12.683386,4.860802,14.551685,9.527630,...,6.891009,3.338660,5.482985,17.276833,6.643182,7.003102,3.735210,4.389217,18.497012,6.654876
8,8.984602,9.748485,2.340716,3.241933,8.340695,8.984602,9.748485,2.340716,3.241933,8.340695,...,0.063114,0.066659,0.103191,0.025847,0.075149,0.054583,0.063767,0.133893,0.023008,0.069099
9,9.866776,2.884397,2.271384,2.457721,9.565298,9.866776,2.884397,2.271384,2.457721,9.565298,...,27.138984,5.146872,8.368728,12.799398,0.703750,5.494081,3.325755,1.746855,3.239867,0.324547
10,14.258715,2.669197,2.232271,2.613961,11.705482,14.258715,2.669197,2.232271,2.613961,11.705482,...,0.475334,0.019257,0.302837,0.000143,823.356487,0.475334,0.019257,0.302837,0.000143,823.356487

In [39]:
adhd_y = pd.Series([1]*len(adhd_Gamma))
adhd_y.index = adhd_Gamma.index
adhd_y

7     1
8     1
9     1
10    1
dtype: int64

- split train and test set

In [42]:
# Theta
train_control_Theta = control_Theta[:4]
train_adhd_Theta = adhd_Theta[:3]
train_Theta = train_control_Theta.append(train_adhd_Theta)

test_control_Theta = control_Theta[4:]
test_adhd_Theta = adhd_Theta[3:]
test_Theta = test_control_Theta.append(test_adhd_Theta)


# Alpha
train_control_Alpha = control_Alpha[:4]
train_adhd_Alpha = adhd_Alpha[:3]
train_Alpha = train_control_Alpha.append(train_adhd_Alpha)

test_control_Alpha = control_Alpha[4:]
test_adhd_Alpha = adhd_Alpha[3:]
test_Alpha = test_control_Alpha.append(test_adhd_Alpha)


# Low_beta
train_control_Low_beta = control_Low_beta[:4]
train_adhd_Low_beta = adhd_Low_beta[:3]
train_Low_beta = train_control_Low_beta.append(train_adhd_Low_beta)

test_control_Low_beta = control_Low_beta[4:]
test_adhd_Low_beta = adhd_Low_beta[3:]
test_Low_beta = test_control_Low_beta.append(test_adhd_Low_beta)


# High_beta
train_control_High_beta = control_High_beta[:4]
train_adhd_High_beta = adhd_High_beta[:3]
train_High_beta = train_control_High_beta.append(train_adhd_High_beta)

test_control_High_beta = control_High_beta[4:]
test_adhd_High_beta = adhd_High_beta[3:]
test_High_beta = test_control_High_beta.append(test_adhd_High_beta)


# Gamma
train_control_Gamma = control_Gamma[:4]
train_adhd_Gamma = adhd_Gamma[:3]
train_Gamma = train_control_Gamma.append(train_adhd_Gamma)

test_control_Gamma = control_Gamma[4:]
test_adhd_Gamma = adhd_Gamma[3:]
test_Gamma = test_control_Gamma.append(test_adhd_Gamma)




# y
train_y = control_y[:4].append(adhd_y[:3])
test_y = control_y[4:].append(adhd_y[3:])

- test

In [46]:
from keras.models import load_model

model = load_model("lstm_model_adults.h5")

Using TensorFlow backend.

In [165]:
# concat_model.save("lstm_model_adults.h5")

In [51]:
len(control_y)

5

In [49]:
print("\n 테스트 정확도: %.4f" % (model.evaluate([control_Theta, control_Alpha, 
                                                  control_Low_beta, control_High_beta, 
                                                    control_Gamma], control_y)[1]))

1/1 [==============================] - 0s 3ms/step - loss: 0.5849 - accuracy: 1.0000

 테스트 정확도: 1.0000

In [52]:
len(adhd_y)

4

In [50]:
print("\n 테스트 정확도: %.4f" % (model.evaluate([adhd_Theta, adhd_Alpha, 
                                                  adhd_Low_beta, adhd_High_beta, 
                                                    adhd_Gamma], adhd_y)[1]))

W0205 07:42:59.321057 14728 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_71:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 07:42:59.324049 14728 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_72:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 07:42:59.328038 14728 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_73:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 07:42:59.332028 14728 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_74:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).
W0205 07:42:59.335019 14728 network.py:957] Model was constructed with shape (None, 1225, 1) for input Tensor("input_75:0", shape=(None, 1225, 1), dtype=float32), but it was called on an input with incompatible shape (None, 490, 1).

1/1 [==============================] - 0s 2ms/step - loss: 0.3225 - accuracy: 0.7500

 테스트 정확도: 0.7500